# Generated by Django 3.2.5 on 2023-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artesoes',
            fields=[
                ('idartesoes', models.AutoField(primary_key=True, serialize=False)),
                ('nome_social', models.CharField(max_length=45)),
                ('sicab', models.CharField(max_length=1, unique=True)),
                ('status_carteira', models.CharField(max_length=7)),
                ('status_cadastro', models.CharField(max_length=7)),
                ('data_cadastro', models.DateField()),
                ('data_validade', models.DateField()),
                ('tipo', models.CharField(max_length=15)),
                ('uf', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('codigo_municipio', models.IntegerField()),
            ],
            options={
                'db_table': 'artesoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaCadastroClient10',
            fields=[
                ('idficha_cadastro_client_1_0', models.AutoField(db_column='idficha_cadastro_client_1.0', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(unique=True)),
                ('identidade', models.CharField(max_length=100, unique=True)),
                ('filiacao_mae', models.CharField(max_length=100)),
                ('profissao', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
            ],
            options={
                'db_table': 'ficha_cadastro_client_1.0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaCadastroCliente13',
            fields=[
                ('idficha_cadastro_cliente_1_3', models.AutoField(db_column='idficha_cadastro_cliente_1.3', primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=45)),
                ('cpnj', models.IntegerField(unique=True)),
                ('inscricao_estadual', models.CharField(max_length=45)),
                ('incricao_municipal', models.CharField(max_length=45)),
                ('data_abertura', models.CharField(max_length=45)),
                ('nome_fantasia', models.CharField(max_length=45)),
                ('setor', models.CharField(max_length=45)),
                ('local', models.CharField(max_length=45)),
                ('ijc', models.CharField(max_length=45)),
                ('endereco_comercial', models.CharField(max_length=45)),
                ('cep', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ficha_cadastro_cliente_1.3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JuntaComercial',
            fields=[
                ('idjunta_comercial', models.AutoField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=100)),
                ('mei', models.CharField(max_length=5)),
                ('cnpj', models.IntegerField(unique=True)),
                ('ds_logradouro', models.CharField(max_length=100)),
                ('ds_numero', models.CharField(max_length=100)),
                ('ds_complemento', models.CharField(max_length=100)),
                ('no_bairro', models.CharField(max_length=100)),
                ('nr_cep', models.CharField(max_length=100)),
                ('no_municipio', models.CharField(max_length=100)),
                ('ds_atividade', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'junta_comercial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Microcredito',
            fields=[
                ('idmicrocredito', models.AutoField(primary_key=True, serialize=False)),
                ('fonte_recursos', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('contratacao', models.CharField(max_length=100)),
                ('carencia', models.CharField(max_length=100)),
                ('quantos_prs', models.CharField(max_length=100)),
                ('valor_prs', models.CharField(max_length=100)),
                ('tac', models.CharField(max_length=100)),
                ('juros', models.CharField(max_length=100)),
                ('giro', models.CharField(max_length=100)),
                ('fixo', models.CharField(max_length=100)),
                ('valor_total', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=100)),
                ('legislacao', models.CharField(max_length=100)),
                ('justificativa', models.CharField(max_length=100)),
                ('empresas_geradas', models.CharField(max_length=100)),
                ('empregos_gerados', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'microcredito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('concat_uf', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('ibge', models.CharField(max_length=45)),
                ('ibge7', models.CharField(max_length=45)),
                ('uf', models.CharField(max_length=45)),
                ('porte', models.CharField(max_length=45)),
                ('capital', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seger',
            fields=[
                ('idseger', models.AutoField(primary_key=True, serialize=False)),
                ('orgao', models.CharField(max_length=100)),
                ('processo', models.CharField(max_length=100)),
                ('processo_finalizado', models.CharField(max_length=5)),
                ('lote', models.CharField(max_length=100)),
                ('lote_excluisivo_me_epp', models.CharField(db_column='lote_excluisivo_me/epp', max_length=5)),
                ('modalidade', models.CharField(max_length=100)),
                ('data_apuracao', models.DateField()),
                ('cpf_cnpj', models.IntegerField(unique=True)),
                ('estado_fornecido', models.CharField(max_length=100)),
                ('natureza_fornecedor', models.CharField(max_length=100)),
                ('fornecedor_me_epp', models.CharField(db_column='fornecedor_me/epp', max_length=100)),
                ('valor_estimado_lote', models.IntegerField()),
                ('valor_apurado', models.IntegerField()),
            ],
            options={
                'db_table': 'seger',
                'managed': False,
            },
        ),
    ]
