# Generated by Django 4.2.1 on 2023-06-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FichaCadastroClient10',
        ),
        migrations.DeleteModel(
            name='FichaCadastroCliente13',
        ),
    ]
